### ISSUE TITLE
Problems with loading CSS locally

### ISSUE THREAD

**Issue by zacharygcook** [zooboole/simple-static-website-with-Slim-3#2]
Unfortunately when you follow your tutorial to build this type of application locally, or even git clone your repo to run the exact code that you have, CSS is not loaded properly. 

I have not run it yet in production, so maybe the issue is fixed there. But how am I going to professionally develop a site without being able to run it locally first?

So my question is - how could you fix this so when the site is ran locally, using a command like `php -S localhost:8080 index.php`, the CSS is loaded correctly?

Below is a screenshot showing some proof:

![selection_038](https://user-images.githubusercontent.com/4422375/30176962-db18949a-93c9-11e7-8180-11b7619ea958.png)

P.S. My local development environment is on Linux - OS Ubuntu 16.04

**Comment by zacharygcook** [comment]
OK, problem was that I was running `php -S localhost:8080 index.php` to run the application instead of simply navigating there from local host, where the app will automatically be run.

When I went to: `http://localhost/____WHATEVER___`, in this case `http://localhost/learning-php/simple-static-website-with-Slim-3/` it worked without any issues. (That starting path location is at the base of my local Apache server, which on my Ubuntu environment is `/var/www/html`)

So that's solves the problem! Hopefully this helps someone else out later.

**Comment by zacharygcook** [comment]
Now I have a problem where routing no longer works... damn this is frustrating. @zooboole you have any ideas on how to solve?

**Comment by anant-svc** [comment]
Do you have .htaccess file on server?

**You .htaccess file should look like this:**
```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /<ROOT FOLDER NAME>/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /<ROOT FOLDER NAME>/index.php [L]
</IfModule>
```

**Comment by anant-svc** [comment]
You could define CONSTANT to store website base url like

`http://127.0.0.1/blog/` - this will be base url and put base url besides css link below.

`http://127.0.0.1/blog/`**css/my-styles.css** - You can load your css files like this.
